<?php

class Model extends Product
{
    protected string $color;
    protected string $model;

    public function __construct(int $id, string $title, string $description, int $price, string $color, string $model)
    {
        parent::__construct($id, $title, $description, $price);
        $this->color = $color;
        $this->model = $model;
    }

    public function renderProduct()
    {
        parent::renderProduct(); // TODO: Change the autogenerated stub
        echo "<p>model: {$this->model} </p> <p>color: {$this->color} </p>";
    }

}